# Generated by Django 3.2.6 on 2021-08-13 07:32
# Adds the Uncategorized category to the database, if there are none

from django.db import migrations


def add_uncategorized_category(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    if Category.objects.count() == 0:
        cat = Category(name="Uncategorized", slug="uncategorized")
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_uncategorized_category),
    ]
